### PR TITLE
foxium compatibility

### PR DESCRIPTION
**Pull request by 1foxy2**
compatibility with foxium (neoforge port of lithium)

### CODE REVIEW

**Comment by jpenilla** [comment]
As mentioned on Discord, I don't have time to keep up with the differences between the various unofficial Lithium ports. If you plan to maintain compatibility through PRs, it makes more sense to have that done in foxium itself, similar to what Radium has done.

**Comment by 1foxy2** [comment]
understandable. at first it had unique id but some mods are hardcoded to lithium mod id, so could you just remove the lithium incompatability?

**Comment by jpenilla** [comment]
I assume you mean Fabric mods loaded through connector? I don't think blanket marking Lithium compatibility is a good idea for a variety of reasons. It would be better to utilize Neo's equivalent of `provides` and adjusting the relevant mod's checks.

**Comment by 1foxy2** [comment]
yes, through connector. the only way to fix incompat (other than mixin into each) i know is either jarjar dummy lithium mod or mixin in modcontainer$getModid to change foxium to lithium, but both will still be incompatible with moonrise.

**Comment by dima-dencep** [comment]
Foxium steal radium patches

**Comment by 1foxy2** [comment]
thats what happens when you don't update mod for 5 months. i also credit radium so i don't see a problem

**Comment by coco875** [comment]
why not just make a PR to update ?

**Comment by 1foxy2** [comment]
i thought radium was dead when making foxium. it is also easier to maintain if its my repo than doing infinite pr and waiting for the maintainer to accept them and publish.

**Comment by 1foxy2** [comment]
i would discontinued foxium but i don't think its 
coincidence what radium stop updated when canary stopped but suddenly got updated when another fork was created

**Comment by dima-dencep** [comment]
I didn't update radium because of a bug in archloom, and I didn't have a server on neoforge

**Comment by 1foxy2** [comment]
then okay, i will discontinue foxium.

**Pull request closed without merging**
